config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    root :to => "main#index"


    resources :main
    resources :posts

    #resources libera as rotas padrões do rails
    # index
    # edit
    # new
    # show
    # destroy
    # crete
    # update
    # action_namespace_controller

    resources :users do
      get :login, on: :collection
      get :logout, on: :collection
      post :do_login, on: :collection
    end

  end

  # action_controller
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_navbar_left.html.erb
<nav>
    <ul class="nav flex-column nav-pills">
        <li class="nav-item"><%= link_to "HOME", admin_main_index_url, class: "nav-link #{"active" if params[:controller] == "admin/main"}" %></li>
        <li class="nav-item"><%= link_to "USER", admin_users_url, class: "nav-link #{"active" if params[:controller] == "admin/users"}" %></li>
        <li class="nav-item"><%= link_to "POST", admin_posts_url, class: "nav-link #{"active" if params[:controller] == "admin/posts"}" %></li>
    </ul>
</nav>

app/views/admin/shared/_system_alerts.html.erb
<% 
    alert_class = ""

flash.each do |type, message| 
    case type.to_s
     when "sucess"
        alert_class = "alert-sucess"
     when "error"
        alert_class = "alert-danger"
     when "alert"
        alert_class = "alert-warning"
     when "notice"
        alert_class = "alert-info"
     else
        alert_class = "alert-secondary"
        end
%>

<%= "<div class='alert #{alert_class}'><p>#{message}</p></div>".html_safe %>

<% end %>